# Generated by Django 4.1.2 on 2022-11-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(max_length=50)),
                ('chat_id', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
    ]
