# Generated by Django 4.1.2 on 2022-11-08 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0002_botdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BotData',
        ),
    ]
