# Generated by Django 4.1.2 on 2022-10-19 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='last_date_load_reviews',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 19, 1, 17, 54, 860028), verbose_name='Последняя дата загрузки отзывов'),
        ),
    ]
