# Generated by Django 4.1.2 on 2022-10-20 12:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_rate_rateinfo_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rateinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='rate',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='last_date_load_reviews',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 20, 2, 11, 57, 650415), verbose_name='Последняя дата загрузки отзывов'),
        ),
    ]
