# Generated by Django 4.1.2 on 2022-11-08 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_branch_address_alter_branch_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='last_date_load_reviews',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 8, 0, 4, 5, 190735), verbose_name='Последняя дата загрузки отзывов'),
        ),
    ]
