# Generated by Django 4.1.2 on 2022-10-20 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_rateinfo_user_rate_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='last_date_load_reviews',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 20, 2, 14, 39, 159119), verbose_name='Последняя дата загрузки отзывов'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='type',
            field=models.IntegerField(choices=[(0, 'Тестовый'), (1, 'Начальный'), (2, 'Средний'), (3, 'Профессиональный')], default=0, max_length=1),
        ),
    ]
