# Generated by Django 4.1.2 on 2022-11-08 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_branch_last_date_load_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='last_date_load_reviews',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 8, 1, 28, 41, 262396), verbose_name='Последняя дата загрузки отзывов'),
        ),
    ]
