# Generated by Django 4.1.2 on 2022-10-07 10:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('description', models.TextField(verbose_name='Описание')),
                ('short_description', models.TextField(verbose_name='Короткое описание')),
                ('last_date_load_reviews', models.DateTimeField(default=datetime.datetime(2022, 10, 6, 21, 1, 32, 887895))),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_start', models.TimeField(verbose_name='Начало работы в Понедельник')),
                ('monday_end', models.TimeField(verbose_name='Окончание работы в Понедельник')),
                ('monday_day_off', models.BooleanField(default=False, verbose_name='Понедельник выходной')),
                ('tuesday_start', models.TimeField(verbose_name='Начало работы во Вторник')),
                ('tuesday_end', models.TimeField(verbose_name='Окончание работы во Вторник')),
                ('tuesday_day_off', models.BooleanField(default=False, verbose_name='Вторник выходной')),
                ('wednesday_start', models.TimeField(verbose_name='Начало работы в Среду')),
                ('wednesday_end', models.TimeField(verbose_name='Окончание работы в Среду')),
                ('wednesday_day_off', models.BooleanField(default=False, verbose_name='Среда выходной')),
                ('thursday_start', models.TimeField(verbose_name='Начало работы в Четверг')),
                ('thursday_end', models.TimeField(verbose_name='Окончание работы в Четверг')),
                ('thursday_day_off', models.BooleanField(default=False, verbose_name='Четверг выходной')),
                ('friday_start', models.TimeField(verbose_name='Начало работы в Пятницу')),
                ('friday_end', models.TimeField(verbose_name='Окончание работы в Пятницу')),
                ('friday_day_off', models.BooleanField(default=False, verbose_name='Пятница выходной')),
                ('saturday_start', models.TimeField(verbose_name='Начало работы в Субботу')),
                ('saturday_end', models.TimeField(verbose_name='Окончание работы в Субботу')),
                ('saturday_day_off', models.BooleanField(default=False, verbose_name='Суббота выходной')),
                ('sunday_start', models.TimeField(verbose_name='Начало работы в Воскресенье')),
                ('sunday_end', models.TimeField(verbose_name='Окончание работы в Воскресенье')),
                ('sunday_day_off', models.BooleanField(default=False, verbose_name='Воскресенье выходной')),
            ],
            options={
                'verbose_name': 'График работы',
                'verbose_name_plural': 'Графики работы',
            },
        ),
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.CreateModel(
            name='Telebot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(max_length=100, verbose_name='ID в Telegram')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telebot_settings', to='core.branch', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Настройки отправки Telegram уведомлений',
            },
        ),
        migrations.CreateModel(
            name='ReviewSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mask', models.TextField(verbose_name='Маска для отзыва')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_settings', to='core.branch', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Настройка автоответов на отзывы',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Полное имя')),
                ('link', models.CharField(max_length=200, verbose_name='Ссылка')),
                ('status', models.CharField(choices=[(0, 'Не прочитано'), (1, 'Прочитано'), (2, 'С ответом')], default=0, max_length=20, verbose_name='Статус')),
                ('rating', models.CharField(choices=[(0, 'Очень плохо'), (1, 'Плохо'), (2, 'Неплохо'), (3, 'Средне'), (4, 'Хорошо'), (5, 'Отлично')], max_length=20, verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branch', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_name', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='QRCode', to='core.branch', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'QRCode',
                'verbose_name_plural': 'QRCodes',
            },
        ),
        migrations.CreateModel(
            name='Connect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(0, 'Yandex'), (1, '2GIS'), (2, 'Google'), (3, 'Flamp'), (4, 'Zoon'), (5, 'Yell')], max_length=20, verbose_name='Платформа')),
                ('key', models.CharField(max_length=100, verbose_name='Ключ для подключения')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Настройка соединения',
                'verbose_name_plural': 'Настройки соединения',
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branchs', to='core.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='branch',
            name='schedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.schedule', verbose_name='График работы'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('body', models.TextField(verbose_name='Ответ на отзыв')),
                ('type', models.CharField(choices=[(0, 'Ответ создан автоматически'), (1, 'Ответ от пользователя')], max_length=100, verbose_name='Тип ответа')),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='core.review', verbose_name='Отзыв')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ на отзыв',
                'verbose_name_plural': 'Ответы на отзывы',
            },
        ),
    ]
