# Generated by Django 4.1.2 on 2022-10-26 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_branch_last_date_load_reviews_alter_rate_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workday',
            options={'verbose_name': 'Рабочий день', 'verbose_name_plural': 'Рабочие дни'},
        ),
        migrations.AlterField(
            model_name='branch',
            name='last_date_load_reviews',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 25, 23, 42, 38, 234041), verbose_name='Последняя дата загрузки отзывов'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='type',
            field=models.IntegerField(choices=[(0, 'Тестовый'), (1, 'Начальный'), (2, 'Средний'), (3, 'Профессиональный')], default=0),
        ),
    ]
