# Generated by Django 4.1.2 on 2022-11-14 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_branch_last_date_load_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Верифицированный аккаунт'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='last_date_load_reviews',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 13, 23, 48, 23, 46716), verbose_name='Последняя дата загрузки отзывов'),
        ),
    ]
