# Generated by Django 4.1.2 on 2022-10-10 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_branch_schedule_alter_company_owner_telebot_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewsettings',
            options={'verbose_name': 'Настройка автоответов на отзывы', 'verbose_name_plural': 'Настройки автоответов на отзывы'},
        ),
        migrations.AlterModelOptions(
            name='telebot',
            options={'verbose_name': 'Настройка отправки Telegram уведомлений', 'verbose_name_plural': 'Настройки отправки Telegram уведомлений'},
        ),
        migrations.AddField(
            model_name='branch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='connect',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='reviewsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='last_date_load_reviews',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 9, 22, 5, 19, 210393), verbose_name='Последняя дата загрузки отзывов'),
        ),
    ]
