# Generated by Django 4.1.2 on 2022-10-26 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_branch_last_date_load_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='last_date_load_reviews',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 25, 23, 46, 3, 717769), verbose_name='Последняя дата загрузки отзывов'),
        ),
    ]
