# Generated by Django 4.1.2 on 2022-11-15 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_is_verified_alter_branch_last_date_load_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='last_date_load_reviews',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 0, 44, 55, 634240), verbose_name='Последняя дата загрузки отзывов'),
        ),
    ]
