# Generated by Django 4.1.2 on 2022-10-11 12:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_reviewsettings_options_alter_telebot_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_the_week', models.PositiveIntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Начало рабочего дня')),
                ('end_time', models.TimeField(max_length=5, verbose_name='Окончание рабочего дня')),
                ('day_type', models.CharField(choices=[('weekday', 'Будний день'), ('holiday', 'Праздничный день'), ('day_off', 'Выходной')], max_length=255, verbose_name='day type')),
            ],
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='friday_day_off',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='friday_end',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='friday_start',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='monday_day_off',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='monday_end',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='monday_start',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='saturday_day_off',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='saturday_end',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='saturday_start',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='sunday_day_off',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='sunday_end',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='sunday_start',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='thursday_day_off',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='thursday_end',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='thursday_start',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='tuesday_day_off',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='tuesday_end',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='tuesday_start',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='wednesday_day_off',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='wednesday_end',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='wednesday_start',
        ),
        migrations.AlterField(
            model_name='branch',
            name='last_date_load_reviews',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 2, 13, 37, 215034), verbose_name='Последняя дата загрузки отзывов'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='friday',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friday', to='core.workday', verbose_name='Пятница'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='monday',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monday', to='core.workday', verbose_name='Понедельник'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='saturday',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saturday', to='core.workday', verbose_name='Суббота'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='sunday',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sunday', to='core.workday', verbose_name='Воскресенье'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='thursday',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thursday', to='core.workday', verbose_name='Четверг'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='tuesday',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuesday', to='core.workday', verbose_name='Вторник'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='wednesday',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wednesday', to='core.workday', verbose_name='Среда'),
        ),
    ]
