# Generated by Django 4.1.2 on 2022-11-15 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_branch_last_date_load_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug для подтверждения'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='last_date_load_reviews',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 1, 59, 31, 784616), verbose_name='Последняя дата загрузки отзывов'),
        ),
    ]
