# Generated by Django 4.1.2 on 2022-11-21 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_branch_last_date_load_reviews_alter_user_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateinfo',
            name='coefficient_for_calculating_the_week',
            field=models.PositiveIntegerField(default=None, verbose_name='Коэффициент для рассчета тарифа на неделю'),
        ),
        migrations.AddField(
            model_name='rateinfo',
            name='coefficient_for_calculating_the_year',
            field=models.PositiveIntegerField(default=None, verbose_name='Коэффициент для рассчета тарифа на неделю'),
        ),
        migrations.AddField(
            model_name='rateinfo',
            name='sale_info',
            field=models.JSONField(default=None, verbose_name='Информация по скидкам'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='last_date_load_reviews',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 0, 56, 30, 985258), verbose_name='Последняя дата загрузки отзывов'),
        ),
        migrations.AlterField(
            model_name='rateinfo',
            name='first_rate',
            field=models.PositiveIntegerField(default=None, verbose_name='Первый тариф'),
        ),
        migrations.AlterField(
            model_name='rateinfo',
            name='second_rate',
            field=models.PositiveIntegerField(default=None, verbose_name='Второй тариф'),
        ),
        migrations.AlterField(
            model_name='rateinfo',
            name='third_rate',
            field=models.PositiveIntegerField(default=None, verbose_name='Третий тариф'),
        ),
    ]
