# Generated by Django 4.1.2 on 2022-12-13 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rateinfo_coefficient_for_calculating_the_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='last_date_load_reviews',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 22, 30, 52, 853174), verbose_name='Последняя дата загрузки отзывов'),
        ),
        migrations.AlterField(
            model_name='rateinfo',
            name='coefficient_for_calculating_the_week',
            field=models.FloatField(default=None, verbose_name='Коэффициент для рассчета тарифа на неделю'),
        ),
        migrations.AlterField(
            model_name='rateinfo',
            name='coefficient_for_calculating_the_year',
            field=models.FloatField(default=None, verbose_name='Коэффициент для рассчета тарифа на год'),
        ),
    ]
