# Generated by Django 4.1.2 on 2022-10-13 13:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_reviewsettings_branch_reviewsettings_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='last_date_load_reviews',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 13, 3, 1, 26, 614787), verbose_name='Последняя дата загрузки отзывов'),
        ),
        migrations.AlterField(
            model_name='reviewsettings',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_settings', to='core.company', verbose_name='Компания'),
        ),
    ]
