# Generated by Django 4.1.2 on 2022-10-17 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_branch_last_date_load_reviews_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='branch',
            name='last_date_load_reviews',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 17, 2, 30, 14, 391869), verbose_name='Последняя дата загрузки отзывов'),
        ),
    ]
