# Generated by Django 4.1.2 on 2022-10-26 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_branch_last_date_load_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='last_date_load_reviews',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 1, 20, 57, 252223), verbose_name='Последняя дата загрузки отзывов'),
        ),
    ]
