# Generated by Django 4.1.2 on 2022-11-01 11:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_branch_last_date_load_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='connect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.connect'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='last_date_load_reviews',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 1, 1, 12, 14, 706249), verbose_name='Последняя дата загрузки отзывов'),
        ),
    ]
