export const REVIEW_CREATE_REQUEST = "REVIEW_CREATE_REQUEST";
export const REVIEW_CREATE_SUCCESS = "REVIEW_CREATE_SUCCESS";
export const REVIEW_CREATE_FAIL = "REVIEW_CREATE_FAIL";

export const REVIEW_DELETE_REQUEST = "REVIEW_DELETE_REQUEST";
export const REVIEW_DELETE_SUCCESS = "REVIEW_DELETE_SUCCESS";
export const REVIEW_DELETE_FAIL = "REVIEW_DELETE_FAIL";

export const REVIEW_ALL_REQUEST = "REVIEW_ALL_REQUEST";
export const REVIEW_ALL_SUCCESS = "REVIEW_ALL_SUCCESS";
export const REVIEW_ALL_FAIL = "REVIEW_ALL_FAIL";

export const REVIEW_LIST_REQUEST = "REVIEW_LIST_REQUEST";
export const REVIEW_LIST_SUCCESS = "REVIEW_LIST_SUCCESS";
export const REVIEW_LIST_FAIL = "REVIEW_LIST_FAIL";

export const REVIEW_ONE_REQUEST = "REVIEW_ONE_REQUEST";
export const REVIEW_ONE_SUCCESS = "REVIEW_ONE_SUCCESS";
export const REVIEW_ONE_FAIL = "REVIEW_ONE_FAIL";

export const REVIEW_UPDATE_REQUEST = "REVIEW_UPDATE_REQUEST";
export const REVIEW_UPDATE_SUCCESS = "REVIEW_UPDATE_SUCCESS";
export const REVIEW_UPDATE_FAIL = "REVIEW_UPDATE_FAIL";
export const REVIEW_UPDATE_RESET = "REVIEW_UPDATE_RESET";